### ISSUE TITLE
ListItemMoveBehaviour for ListView

### ISSUE THREAD

**Issue by c0nnex** [aelij/WPFContrib#1]
I fixed some problems there.
Unfortunately i forgot to branch, so I cannot create a pull request.

dba54e72d52b21d52839cd393a2348b90324bf33
92a45e3385a688e186e9c946710199c56efb0902
4ffe3415350369e8a2dda74e26c2ba26da27ce36

**Comment by aelij** [comment]
These changes look good. You can create a pull request from the master in your fork.

**Comment by c0nnex** [comment]
Have you looked at my master? There are 3 other commits concerning the NotifyIcon. I don't know if those are wanted. 
If yes, I'll create a complete pull request
if no, I'll revert and start from scratch branching off the ListItemMoveBehavior changes.

**Comment by aelij** [comment]
Oh. I'm afraid I don't like the icon change. The entire purpose of the NotifyIcon class was to use native WPF APIs instead of Windows Form's.

Then please only include only the above changes. Thanks!

**Comment by aelij** [comment]
Fixed in #2
