### ISSUE TITLE
Make FolderBrowserDialog main title changable

### ISSUE THREAD

**Issue by romaromaniv** [aelij/WPFContrib#4]
Hi,

at the moment FolderBrowserDialog has property Title, however it is not main title of the modal window. Please see screenshot.

![image](https://user-images.githubusercontent.com/28062488/58754657-eff59a00-84dd-11e9-85e4-95c5afdf2191.png)

I would like to change main title as well.

**Comment by aelij** [comment]
I'm afraid we're limited by the Windows dialog API. I don't know of a way to do this.
